albertms10/music_notes

lib/src/classes/enharmonic_note.dart
lib/src/classes/key_signature.dart
lib/src/classes/note.dart
lib/src/classes/relative_tonalities.dart
lib/src/classes/tonality.dart
lib/src/utils/music.dart

docs: reference new `Accidental` class instead of enum

---

.github/workflows/analysis-ci.yml
pubspec.yaml

Also, the `pubspec.yaml` file will serve as the cache key for the Analysis CI workflow. As a library package, committing `pubspec.lock` is discouraged and, thus, unavailable at that point. See [Private files](https://dart.dev/guides/libraries/private-files#pubspeclock).
Fixes #7

chore(pubspec): bump version 0.3.0

---

lib/src/note/accidental.dart
test/src/note/accidental_test.dart

The method was previously removed in #8.

feat(accidental): bring `increment` method back

---

lib/src/note/note.dart
test/src/tonality/key_signature_test.dart

Fixes failing tests introduced in #26

fix(note): simplify `fromRawAccidentals` accidental increment

---

lib/src/note/note.dart
test/src/main.dart
test/src/note/note_test.dart

Adds missing `notes_test.main()` call from #54.

test(note): add test cases for `difference`

---

lib/src/interval/quality.dart
test/src/interval/enharmonic_interval_test.dart
test/src/interval/interval_test.dart
test/src/interval/quality_test.dart

- add triply diminished and augmented static const constructors.

refactor(quality)!: rename `double` to `doubly`

---

lib/music_notes.dart
lib/src/note/frequency.dart
lib/src/note/positioned_note.dart
test/src/main.dart
test/src/note/frequency_test.dart
test/src/note/positioned_note_test.dart

This is to separate concerns: converting the positioned note to a frequency, which could be done in different ways, e.g. equal tempered, pythagorean (these methods belong to PositionedNote),
versus properties or functionality related to the frequency itself, such as isHumanAudible or a hypothetical .play() method.
Closes #107

refactor: Extract Frequency

---

lib/src/note/note.dart
lib/src/note/positioned_note.dart
test/src/note/positioned_note_test.dart

Closes #106 
Comments:
- Now that `semitones` doesn't collide with `Note.semitones`, I renamed `semitonesFromRootHeight` to `semitones` to conform with `MusicItem`, but perhaps you prefer keeping the more explicit name and adding an alias `semitones => semitonesFromRootHeight`?
- Should I implement the `Transposable<T>` definition change in this PR now that it is easier, or in a separate one?

refactor: PositionedNote composition with Note instead of inheritance

---

lib/src/scale/scale_pattern.dart
test/src/scale/scale_pattern_test.dart
test/src/scale/scale_test.dart

fix(scale_pattern): return correct descending `PositionedNote` scale in `from`

---

test/src/interval/enharmonic_interval_test.dart

test(enharmonic_interval): add test cases for `isDescending`, `descending` methods

---

lib/src/note/positioned_note.dart
test/src/note/positioned_note_test.dart

fix(positioned_note): use correct `hashCode` values

---

lib/src/interval/interval_size_extension.dart
test/src/interval/interval_size_extension_test.dart
test/src/note/positioned_note_test.dart

fix(interval_size_extension): return correct `semitones` for large intervals

---

lib/src/note/note.dart
test/src/note/note_test.dart

:bug: fix(note): return correct distance for extreme Note spellings

---

lib/music_notes.dart
lib/src/note/enharmonic_note.dart
test/src/note/enharmonic_note_test.dart

Use `Interval.distanceBetween` instead.

:fire: refactor(enharmonic_note)!: remove `shortestFifthsDistance` methods

---

lib/src/note/note.dart
lib/src/note/positioned_note.dart
test/src/note/positioned_note_test.dart

**Breaking change:** `octave` argument in the `PositionedNote` constructor is now named and no longer has a default value.

:recycle: refactor(positioned_note)!: make `octave` argument required

---

lib/src/note/note.dart

:book: docs(note): update missing `inOctave` examples

---

lib/src/note/base_note.dart
lib/src/note/enharmonic_note.dart
lib/src/note/note.dart
lib/src/note/positioned_note.dart
lib/utils/int_extension.dart
test/src/note/note_test.dart
test/src/note/positioned_note_test.dart
test/utils/int_extension_test.dart

:boom: refactor(note): rewrite semitones starting from 0 instead of 1

---

lib/src/interval/interval.dart
lib/src/interval/interval_class.dart
lib/src/note/base_note.dart
lib/src/note/note.dart
lib/src/note/pitch_class.dart
lib/utils/int_extension.dart
test/utils/int_extension_test.dart

This PR aims to:
- remove `chromaticMod` in favor of its explicit `% chromaticDivisions` usage
- rename `nModExcludeZero` → `nonZeroMod`

:recycle: refactor(int_extension): simplify modulo methods

---

lib/src/note/accidental.dart
lib/src/note/base_note.dart
lib/src/note/note.dart
test/src/note/accidental_test.dart
test/src/note/base_note_test.dart

See https://github.com/albertms10/music_notes/pull/127#pullrequestreview-1429403495

✨ feat(accidental): add `operator +-`

---

lib/src/note/note.dart
lib/src/note/positioned_note.dart
test/src/harmony/chord_test.dart
test/src/note/note_test.dart
test/src/note/positioned_note_test.dart

:boom: fix(note): remove `semitones` chromatic modulo

---

lib/src/harmony/chord.dart
lib/src/harmony/chord_pattern.dart
lib/src/scalable.dart
lib/src/scale/scale.dart

Although `dart doc` builds references as expected, IDE reference navigation does not work.

docs: :book: remove type parameter references in doc comments

---

.vscode/settings.json
lib/src/harmony/chord.dart
lib/src/harmony/chord_pattern.dart
lib/src/interval/quality.dart
lib/src/note/base_note.dart
lib/src/note/frequency.dart
lib/src/note/note.dart
lib/src/tonality/mode.dart
lib/src/tonality/tonality.dart
test/src/note/note_test.dart
test/src/tonality/mode_test.dart
test/src/tonality/tonality_test.dart

This PR also replaces `NoteNotation.catalan` by its parent `NoteNotation.italian` system.

refactor!(note): :recycle: rename `NotationSystem` → `NoteNotation`

---

.gitignore

Following the Dart language guidelines on [Creating packages](https://dart.dev/guides/libraries/create-packages#providing-additional-files), the `bin` directory should contain any command-line tools intended for public consumption, whilst any tools or executables created during development that aren’t for public use should go under the `tool` directory.

chore(gitignore): 🙈 ignore the `tool` directory instead of `bin`

---

lib/src/interval/quality.dart

refactor(quality): ♻️ move diminished and augmented symbols to `Quality`

---

README.md
example/main.dart

docs(README): 📖 remove unit symbol from `Frequency` examples 

---

lib/src/enharmonic.dart
lib/src/interval/interval.dart
lib/src/interval/interval_class.dart
lib/src/note/note.dart
lib/src/scalable.dart
lib/src/scale/scale.dart
lib/src/scale/scale_pattern.dart
test/src/note/note_test.dart

This is the second attempt to revive the `Enharmonic` entity (see #194 and #250).
The difference between the older approach (#250) is that instead of being a superclass of both `PitchClass` and `IntervalClass`, it is designed as a mixin for `Note`, `Pitch`, and `Interval` classes to tell which _enharmonic_ entity they're related to.

refactor(enharmonic): ♻️ rename `ClassMixin` → `Enharmonic` mixin

---

lib/src/interval/interval.dart
lib/src/interval/interval_class.dart
lib/src/interval/size.dart
lib/src/note/note.dart
lib/src/note/pitch.dart
test/src/interval/interval_test.dart
test/src/interval/size_test.dart

Closes #475 
Rename:
- `fromQualitySemitones` -> `fromSizeAndQualitySemitones`
- `fromSemitones` -> `fromSizeAndSemitones`
Add:
- `fromSemitones(int)`

feat!(interval): ✨ add `fromSemitones(int)` and rename `fromSizeAndSemitones` factory constructors

---

lib/src/interval/interval.dart

After https://github.com/dart-lang/linter/issues/4978 is fixed

refactor(interval): 📖 remove ignored `prefer_const_constructors` lint

---

lib/src/interval/size.dart
test/src/interval/interval_test.dart

fix(size): 🐛 rewrite `semitones` getter without relying on deprecated `absShift`

---

lib/src/interval/size.dart
test/src/interval/size_test.dart

fix(size): 🐛 use correct `isPerfect` assert condition in constructor

---

test/src/interval/quality_test.dart

test(quality): 🧪 add missing test case for `compareTo` method

---

lib/src/scale/scale_pattern.dart
test/src/scale/scale_pattern_test.dart

Add lydianAugmented with getting the name of the default scale patterns

feat(scale_pattern): ✨ add Lydian augmented `name`
